App\Entity\User:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 3

    email:
      - NotBlank: ~
      - Email:

    password:
      - NotBlank: ~
      - Length:
          min: 6
