index:
    path: /
    controller: App\Controller\HomeController::index
login:
    path: /login
    controller: App\Controller\SecurityController::login
register:
    path: /register
    controller: App\Controller\SecurityController::register
