index:
    path: /
    controller: App\Controller\HomeController::index
login:
    path: /login
    controller: App\Controller\SecurityController::login
register:
    path: /register
    controller: App\Controller\SecurityController::register
register_process:
    path: /register_process
    controller: App\Controller\SecurityController::register_process
inscription:
    path: /inscription
    controller: App\Controller\RegisterController::index